import '../styles/globals.scss';

import { Breadcrumb, Button, Layout, Menu } from 'antd';
import { Footer } from 'antd/lib/layout/layout';
import type { AppProps } from 'next/app';
import { useRouter } from 'next/dist/client/router';
import Head from 'next/head';

import classes from './App.module.scss';
const { Header, Content } = Layout;

const App = ({ Component, pageProps }: AppProps) => {
  const router = useRouter();

  const homeClickHandler = () => router.push('/');
  const eventsClickHandler = () => router.push('/events');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header>
          <Menu theme="dark" mode="horizontal">
            <Menu.Item onClick={homeClickHandler}>Home</Menu.Item>
            <Menu.Item onClick={eventsClickHandler}>Events</Menu.Item>
          </Menu>
        </Header>
        <Content className={classes['layout__content__wrapper']}>
          <Breadcrumb className={classes['breadcrumb']}>
            <Breadcrumb.Item>Home</Breadcrumb.Item>
          </Breadcrumb>
          <div className={classes['layout__content']}>
            <Component {...pageProps} />
          </div>
        </Content>
        <Footer className={classes['footer']}>
          Events app developed for Udemy&apos;s NextJS course
        </Footer>
      </Layout>
    </>
  );
};
export default App;
