import '../styles/globals.scss';

import { Layout } from 'antd';
import { Footer } from 'antd/lib/layout/layout';
import type { AppProps } from 'next/app';
import Head from 'next/head';

import { Breadcrumbs } from '../components/layout/breadcrumbs';
import { Navbar } from '../components/layout/navbar';
import classes from './App.module.scss';
const { Header, Content } = Layout;

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout className={classes['layout']}>
        <Header>
          <Navbar />
        </Header>
        <Content className={classes['layout__content__wrapper']}>
          <Breadcrumbs />
          <div className={classes['layout__content']}>
            <Component {...pageProps} />
          </div>
        </Content>
        <Footer className={classes['footer']}>
          Events app developed for Udemy&apos;s NextJS course
        </Footer>
      </Layout>
    </>
  );
};
export default App;
